version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      antv-x6:
        patterns:
          - '@antv/x6'
          - '@antv/x6-*'
        update-types: [minor, patch]
      non-breaking-changes:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    groups:
      non-breaking-changes:
        update-types: [minor, patch]
