import { defineConfig } from '@vben/oxfmt-config';

export default defineConfig({
  ignorePatterns: [
    'dist',
    'dev-dist',
    '.local',
    '.claude',
    '.agent',
    '.agents',
    '.github',
    '.codex',
    '.output.js',
    'node_modules',
    '.nvmrc',
    'coverage',
    'CODEOWNERS',
    '.nitro',
    '.output',
    '**/*.svg',
    '**/*.sh',
    'public',
    '.npmrc',
    '*-lock.yaml',
    'skills-lock.json',
    // Upstream-owned source is verified byte-for-byte by the FDM boundary guard.
    // Excluding it here prevents a local formatter release from rewriting the
    // pinned official tree during an ordinary FDM change.
    'apps/backend-mock',
    'apps/web-antdv-next',
    'apps/web-ele',
    'apps/web-naive',
    'apps/web-tdesign',
    'apps/web-antd/src/components',
    'apps/web-antd/src/api/{ai,bpm,crm,erp,fms,hrm,im,iot,mall,member,mes,mp,pay,product,promotion,report,system,wms}',
    'apps/web-antd/src/views/{ai,bpm,crm,erp,fms,hrm,im,iot,mall,member,mes,mp,pay,product,promotion,report,system,wms}',
    'apps/web-antd/src/router/routes/modules/{ai,mes}.ts',
    'apps/web-antd/src/api/fdmdata',
    'apps/web-antd/src/api/fdmxui',
    'apps/web-antd/src/views/dashboard',
    'apps/web-antd/src/views/{fdmai,fdmcaiwu,fdmcreative,fdmdata,fdmdingtalk,fdmneixiao,fdmperformance,fdmxui}',
    'apps/web-antd/e2e/fixtures/FdmCreativeWorkbenchFixture.vue',
    'packages',
    'docs/src/guide/fdmcreative',
  ],
});
