import type { TradePrototypeState } from './types';

export const MAIN_ORDER_ID = 'SO-FTM-202608-018';
export const FORMULA_ORDER_ID = 'SO-FTM-202608-1000';
export const FULFILMENT_ORDER_ID = 'SO-FTM-202607-011';

/**
 * The seed intentionally contains one coherent order journey plus completed
 * examples for every prototype page. It is a factory so gateway resets never
 * share mutable array references.
 */
export function createTradePrototypeSeed(): TradePrototypeState {
  return {
    schemaVersion: 2,
    customers: [
      {
        id: 'CUS-1001',
        code: 'FT-CUS-00018',
        country: '德国',
        firstOrderDate: '2025-03-18',
        level: 'A',
        name: 'NOVA FITNESS GMBH',
        okkiOwner: 'Linda Zhou',
        okkiSerialId: 'OKKI-00818',
        orderCount: 8,
        outstandingAmount: '86500.00',
        owner: '林晓月',
        syncStatus: 'SYNCED',
        transactionAmount: '512900.00',
      },
      {
        id: 'CUS-1002',
        code: 'FT-CUS-00026',
        country: '美国',
        firstOrderDate: '2024-11-09',
        level: 'A',
        name: 'Northstar Fitness LLC',
        okkiOwner: 'Linda Zhou',
        okkiSerialId: 'OKKI-00863',
        orderCount: 12,
        outstandingAmount: '45010.00',
        owner: '周雨晴',
        syncStatus: 'SYNCED',
        transactionAmount: '628400.00',
      },
      {
        id: 'CUS-1004',
        code: 'FT-CUS-00100',
        country: '英国',
        firstOrderDate: '2026-08-01',
        level: 'B',
        name: 'Balance Lab Trading Ltd',
        okkiOwner: 'Steven Liu',
        okkiSerialId: 'OKKI-01000',
        orderCount: 1,
        outstandingAmount: '280.00',
        owner: '陈静',
        syncStatus: 'SYNCED',
        transactionAmount: '1000.00',
      },
    ],
    contacts: [
      {
        id: 'CONT-1001',
        customerId: 'CUS-1001',
        email: 'anna@nova-fitness.example',
        isPrimary: true,
        name: 'Anna Keller',
        phone: '+49 40 5550 1818',
        source: 'OKKI',
      },
      {
        id: 'CONT-1002',
        customerId: 'CUS-1002',
        email: 'emma@northstar-fitness.example',
        isPrimary: true,
        name: 'Emma Wilson',
        phone: '+1 310 555 0011',
        source: 'OKKI',
      },
      {
        id: 'CONT-1004',
        customerId: 'CUS-1004',
        email: 'finance@balance-lab.example',
        isPrimary: true,
        name: 'Oliver Smith',
        phone: '+44 20 7946 0100',
        source: 'OKKI',
      },
    ],
    okkiCustomers: [
      {
        id: 'OKKI-C-0818',
        companyId: 'company_908181',
        contactEmail: 'anna@nova-fitness.example',
        contactName: 'Anna Keller',
        contactPhone: '+49 40 5550 1818',
        country: '德国',
        mappedCustomerId: 'CUS-1001',
        name: 'NOVA FITNESS GMBH',
        owner: 'Linda Zhou',
        serialId: 'OKKI-00818',
        stage: '已成交',
      },
      {
        id: 'OKKI-C-0981',
        companyId: 'company_919811',
        contactEmail: 'camille@alpine-studio.example',
        contactName: 'Camille Laurent',
        contactPhone: '+33 1 55 55 09 81',
        country: '法国',
        name: 'Alpine Studio SAS',
        owner: 'Linda Zhou',
        serialId: 'OKKI-00981',
        stage: '准备下单',
      },
      {
        id: 'OKKI-C-0993',
        companyId: 'company_921204',
        contactEmail: 'erik@nordic-balance.example',
        contactName: 'Erik Lindström',
        contactPhone: '+46 8 555 09 93',
        country: '瑞典',
        name: 'Nordic Balance AB',
        owner: 'Steven Liu',
        serialId: 'OKKI-00993',
        stage: '准备下单',
      },
    ],
    orders: [
      {
        id: MAIN_ORDER_ID,
        additionalFee: '1850.00',
        company: '飞德慕国际贸易有限公司',
        currency: 'USD',
        customerId: 'CUS-1001',
        destinationPort: 'Hamburg, Germany',
        exchangeRate: '7.18',
        incoterm: 'FOB Shanghai',
        lines: [
          {
            id: 'SOL-018-01',
            amount: '65000.00',
            availableStockQty: '500',
            customerSku: 'NOVA-YM-6001',
            packagingVersion: 'PKG-V4',
            productName: '6mm TPE 瑜伽垫',
            productVersion: 'TPE-2026-V2',
            quantity: '5000',
            sku: 'MAT-TPE-06',
            specification: '1830 × 610 × 6 mm / 深海蓝 / 定制激光纹',
            suggestedFactoryQty: '4500',
            suggestedPurchaseQty: '0',
            suggestedStockQty: '500',
            unit: '张',
            unitPrice: '13.00',
          },
          {
            id: 'SOL-018-02',
            amount: '12000.00',
            availableStockQty: '0',
            customerSku: 'NOVA-YB-2202',
            packagingVersion: 'BOX-2PCS-V3',
            productName: '软木瑜伽砖',
            productVersion: 'CORK-2026-V1',
            quantity: '2000',
            sku: 'BRICK-CORK-01',
            specification: '230 × 150 × 76 mm / 2 只装 / 原木色',
            suggestedFactoryQty: '0',
            suggestedPurchaseQty: '2000',
            suggestedStockQty: '0',
            unit: '只',
            unitPrice: '6.00',
          },
          {
            id: 'SOL-018-03',
            amount: '7650.00',
            availableStockQty: '100',
            customerSku: 'NOVA-PKG-4004',
            packagingVersion: 'CUSTOMER-V4',
            productName: '五层出口纸箱',
            productVersion: 'CTN-2026-V2',
            quantity: '5100',
            sku: 'CTN-EXPORT-05',
            specification: '五层瓦楞 / 客户包装 V4 / 含 2% 备品',
            suggestedFactoryQty: '0',
            suggestedPurchaseQty: '5000',
            suggestedStockQty: '100',
            unit: '只',
            unitPrice: '1.50',
          },
        ],
        originPort: '上海港',
        owner: '林晓月',
        paymentTerms: '30% 定金，70% 出货前',
        requiredShipAt: '2026-10-20',
        risk: 'MEDIUM',
        signedAt: '2026-08-27',
        status: 'IN_PROGRESS',
        totalAmount: '86500.00',
        type: 'BULK',
      },
      {
        id: FULFILMENT_ORDER_ID,
        additionalFee: '0.00',
        company: '飞德慕国际贸易有限公司',
        currency: 'USD',
        customerId: 'CUS-1002',
        destinationPort: 'Los Angeles, USA',
        exchangeRate: '7.16',
        incoterm: 'FOB Wuhan',
        lines: [
          {
            id: 'SOL-011-01',
            amount: '44800.00',
            availableStockQty: '400',
            customerSku: 'NS-TPE-2400',
            packagingVersion: 'NS-BOX-V2',
            productName: '双层 TPE 瑜伽垫',
            productVersion: 'TPE-2026-V1',
            quantity: '2800',
            sku: 'MAT-TPE-08',
            specification: '1830 × 610 × 8 mm / 灰紫双色',
            suggestedFactoryQty: '2400',
            suggestedPurchaseQty: '0',
            suggestedStockQty: '400',
            unit: '张',
            unitPrice: '16.00',
          },
          {
            id: 'SOL-011-02',
            amount: '12000.00',
            availableStockQty: '0',
            customerSku: 'NS-CORK-2000',
            packagingVersion: 'BOX-2PCS-V3',
            productName: '软木瑜伽砖',
            productVersion: 'CORK-2026-V1',
            quantity: '2000',
            sku: 'BRICK-CORK-01',
            specification: '230 × 150 × 76 mm / 2 只装 / 原木色',
            suggestedFactoryQty: '0',
            suggestedPurchaseQty: '2000',
            suggestedStockQty: '0',
            unit: '只',
            unitPrice: '6.00',
          },
          {
            id: 'SOL-011-03',
            amount: '7500.00',
            availableStockQty: '0',
            customerSku: 'NS-PKG-5000',
            packagingVersion: 'NS-BOX-V2',
            productName: '五层出口纸箱',
            productVersion: 'CTN-2026-V2',
            quantity: '5000',
            sku: 'CTN-EXPORT-05',
            specification: '五层瓦楞 / Northstar 包装 V2',
            suggestedFactoryQty: '0',
            suggestedPurchaseQty: '5000',
            suggestedStockQty: '0',
            unit: '只',
            unitPrice: '1.50',
          },
        ],
        originPort: '上海港',
        owner: '周雨晴',
        paymentTerms: '30% 定金，提单副本后付清尾款',
        requiredShipAt: '2026-09-24',
        risk: 'HIGH',
        signedAt: '2026-07-18',
        status: 'PARTIALLY_SHIPPED',
        totalAmount: '64300.00',
        type: 'BULK',
      },
      {
        id: FORMULA_ORDER_ID,
        additionalFee: '0.00',
        company: '飞德慕国际贸易有限公司',
        currency: 'USD',
        customerId: 'CUS-1004',
        destinationPort: 'Felixstowe, UK',
        exchangeRate: '7.18',
        incoterm: 'FOB Shanghai',
        lines: [
          {
            id: 'SOL-1000-01',
            amount: '1000.00',
            availableStockQty: '100',
            productName: '演示订单组合产品',
            quantity: '100',
            sku: 'DEMO-BUNDLE-100',
            specification: '回款与冲销口径演示',
            suggestedFactoryQty: '0',
            suggestedPurchaseQty: '0',
            suggestedStockQty: '100',
            unit: '套',
            unitPrice: '10.00',
          },
        ],
        originPort: '上海港',
        owner: '陈静',
        paymentTerms: '分批回款',
        requiredShipAt: '2026-09-15',
        risk: 'LOW',
        signedAt: '2026-08-01',
        status: 'IN_PROGRESS',
        totalAmount: '1000.00',
        type: 'BULK',
      },
    ],
    demandAnalyses: [
      {
        id: 'DA-011',
        confirmedAt: '2026-07-19T03:20:00.000Z',
        confirmedBy: '周雨晴',
        generatedAt: '2026-07-19T03:05:00.000Z',
        lines: [
          {
            id: 'DAL-011-01',
            confidence: '0.97',
            factoryQty: '2400',
            orderLineId: 'SOL-011-01',
            purchaseQty: '0',
            stockQty: '400',
            strategy: '武汉仓现货 + 洛阳工厂供货',
          },
          {
            id: 'DAL-011-02',
            confidence: '0.93',
            factoryQty: '0',
            orderLineId: 'SOL-011-02',
            purchaseQty: '2000',
            stockQty: '0',
            strategy: '宁波供应商外部采购',
          },
          {
            id: 'DAL-011-03',
            confidence: '0.88',
            factoryQty: '0',
            orderLineId: 'SOL-011-03',
            purchaseQty: '5000',
            stockQty: '0',
            strategy: '东莞供应商定制包装',
          },
        ],
        orderId: FULFILMENT_ORDER_ID,
        status: 'CONFIRMED',
      },
    ],
    suppliers: [
      {
        id: 'SUP-0028',
        categories: ['瑜伽砖', '软木制品'],
        contactName: '王海峰',
        currentLoad: '68%',
        name: '宁波绿动运动用品有限公司',
        onTimeRate: '0.97',
        paymentTerms: '30% 定金，验货后付尾款',
        phone: '13800000028',
        qualityRate: '0.992',
        quotes: [
          {
            id: 'QUOTE-0028-CORK',
            currency: 'CNY',
            leadTimeDays: 18,
            minimumOrderQty: '1000',
            sku: 'BRICK-CORK-01',
            unitPrice: '2.84',
            validUntil: '2026-09-30',
            version: 'CORK-2026-V1',
          },
        ],
        risk: 'LOW',
        status: 'APPROVED',
      },
      {
        id: 'SUP-0016',
        categories: ['瑜伽砖', '健身配件'],
        contactName: '李梦',
        currentLoad: '86%',
        name: '义乌跃能文体有限公司',
        onTimeRate: '0.89',
        paymentTerms: '50% 定金，出货前付尾款',
        phone: '13800000016',
        qualityRate: '0.985',
        quotes: [
          {
            id: 'QUOTE-0016-CORK',
            currency: 'CNY',
            leadTimeDays: 24,
            minimumOrderQty: '800',
            sku: 'BRICK-CORK-01',
            unitPrice: '2.76',
            validUntil: '2026-09-20',
            version: 'CORK-2026-V1',
          },
        ],
        risk: 'MEDIUM',
        status: 'APPROVED',
      },
      {
        id: 'SUP-0041',
        categories: ['出口包装', '纸箱'],
        contactName: '张磊',
        currentLoad: '54%',
        name: '东莞衡健实业有限公司',
        onTimeRate: '0.95',
        paymentTerms: '月结 30 天',
        phone: '13800000041',
        qualityRate: '0.976',
        quotes: [
          {
            id: 'QUOTE-0041-CTN',
            currency: 'CNY',
            leadTimeDays: 16,
            minimumOrderQty: '3000',
            sku: 'CTN-EXPORT-05',
            unitPrice: '1.18',
            validUntil: '2026-09-25',
            version: 'CTN-2026-V2',
          },
        ],
        risk: 'MEDIUM',
        status: 'APPROVED',
      },
    ],
    purchaseRequisitions: [
      {
        id: 'PR-202608-011',
        confirmedAt: '2026-08-19T04:00:00.000Z',
        createdAt: '2026-08-19T03:30:00.000Z',
        lines: [
          {
            id: 'PRL-011-01',
            orderLineId: 'SOL-011-02',
            productName: '软木瑜伽砖',
            quantity: '2000',
            selectedSupplierId: 'SUP-0028',
            sku: 'BRICK-CORK-01',
            suggestions: [
              {
                confidence: '0.93',
                reason: '同类产品近 12 个月交付稳定，报价与产能匹配。',
                supplierId: 'SUP-0028',
              },
              {
                confidence: '0.86',
                reason: '价格较低，但近期有两次延期。',
                supplierId: 'SUP-0016',
              },
            ],
            unit: '只',
          },
        ],
        orderId: FULFILMENT_ORDER_ID,
        requiredAt: '2026-10-01',
        risk: '包装版本需在下单前复核',
        status: 'SOURCED',
      },
      {
        id: 'PR-202608-012',
        confirmedAt: '2026-08-19T04:00:00.000Z',
        createdAt: '2026-08-19T03:30:00.000Z',
        lines: [
          {
            id: 'PRL-012-01',
            orderLineId: 'SOL-011-03',
            productName: '五层出口纸箱',
            quantity: '5000',
            sku: 'CTN-EXPORT-05',
            suggestions: [
              {
                confidence: '0.81',
                reason: '交期快且账期友好，首次供应 V4 包装需要首件确认。',
                supplierId: 'SUP-0041',
              },
            ],
            unit: '只',
          },
        ],
        orderId: FULFILMENT_ORDER_ID,
        requiredAt: '2026-10-01',
        risk: '客户包装 V4 待首件确认',
        status: 'CONFIRMED',
      },
    ],
    purchaseOrders: [
      {
        id: 'PO-202608-028',
        currency: 'CNY',
        expectedAt: '2026-09-22',
        invoicedAmount: '0.00',
        items: [
          {
            id: 'POI-028-01',
            amount: '5680.00',
            orderLineId: 'SOL-011-02',
            productName: '软木瑜伽砖',
            quantity: '2000',
            requisitionLineId: 'PRL-011-01',
            sku: 'BRICK-CORK-01',
            unit: '只',
            unitPrice: '2.84',
          },
        ],
        orderId: FULFILMENT_ORDER_ID,
        paidAmount: '1704.00',
        requisitionId: 'PR-202608-011',
        status: 'IN_PRODUCTION',
        supplierId: 'SUP-0028',
        totalAmount: '5680.00',
      },
    ],
    factoryTasks: [
      {
        id: 'FT-202607-011',
        completedQty: '1800',
        estimatedReadyAt: '2026-09-06',
        factory: '洛阳飞德慕工厂',
        orderId: FULFILMENT_ORDER_ID,
        orderLineId: 'SOL-011-01',
        owner: '王工',
        requiredAt: '2026-09-10',
        requiredQty: '2400',
        status: 'IN_PROGRESS',
      },
    ],
    followUpTasks: [
      {
        id: 'FUP-202608-011',
        aiReadiness: 'BLOCKED',
        aiReadinessMessage: '缺少最终装箱单，AI 仅提示风险，未替代报关确认。',
        customsDocuments: [
          { id: 'DOC-CI-011', label: '商业发票', status: 'READY' },
          { id: 'DOC-PL-011', label: '装箱单最终版', status: 'MISSING' },
          { id: 'DOC-DC-011', label: '报关要素', status: 'READY' },
        ],
        lastAiCheckedAt: '2026-08-27T02:15:00.000Z',
        milestones: [
          {
            id: 'MS-011-01',
            completedAt: '2026-08-25T08:00:00.000Z',
            label: '供应方确认',
            status: 'COMPLETED',
          },
          { id: 'MS-011-02', label: '订舱', status: 'PENDING' },
          { id: 'MS-011-03', label: '海关放行', status: 'PENDING' },
        ],
        orderId: FULFILMENT_ORDER_ID,
        owner: '赵敏',
        purchaseOrderIds: [],
        shipmentId: 'SH-202608-011',
        stage: 'CUSTOMS_PREPARATION',
        status: 'IN_PROGRESS',
      },
    ],
    shipments: [
      {
        id: 'SH-202608-011',
        batch: '第一批',
        createdAt: '2026-08-24T06:00:00.000Z',
        eta: '2026-10-03',
        etd: '2026-09-14',
        lines: [
          {
            id: 'SHL-011-01',
            orderLineId: 'SOL-011-01',
            quantity: '2400',
            sources: [
              {
                quantity: '2400',
                sourceId: 'FT-202607-011',
                sourceLocation: '洛阳飞德慕工厂',
                sourceType: 'FACTORY',
              },
            ],
          },
        ],
        orderId: FULFILMENT_ORDER_ID,
        progress: '0.72',
        status: 'CUSTOMS_PREPARATION',
      },
    ],
    inboundDocuments: [
      {
        id: 'IN-202608-028-A',
        items: [
          { id: 'INI-028-01', orderLineId: 'SOL-011-02', quantity: '800' },
        ],
        purchaseOrderId: 'PO-202608-028',
        receivedAt: '2026-08-26T07:10:00.000Z',
        status: 'CONFIRMED',
        warehouse: '武汉成品仓',
      },
    ],
    outboundDocuments: [
      {
        id: 'OUT-202608-011-LY',
        items: [
          { id: 'OUTI-011-01', orderLineId: 'SOL-011-01', quantity: '2400' },
        ],
        location: '洛阳飞德慕工厂',
        orderId: FULFILMENT_ORDER_ID,
        shipmentId: 'SH-202608-011',
        status: 'DRAFT',
      },
    ],
    receipts: [
      {
        id: 'RC-202608-1000',
        account: '中国银行武汉分行 · USD 账户',
        amount: '600.00',
        cnyAmount: '4308.00',
        currency: 'USD',
        payer: 'Balance Lab Trading Ltd',
        rate: '7.18',
        receivedAt: '2026-08-18',
        status: 'CONFIRMED',
      },
      {
        id: 'RC-202608-011',
        account: '招商银行武汉分行 · USD 账户',
        amount: '19290.00',
        cnyAmount: '138116.40',
        currency: 'USD',
        payer: 'Northstar Fitness LLC',
        rate: '7.16',
        receivedAt: '2026-08-18',
        status: 'CONFIRMED',
      },
    ],
    receiptAllocations: [
      {
        id: 'RA-202608-1000',
        amount: '600.00',
        orderId: FORMULA_ORDER_ID,
        receiptId: 'RC-202608-1000',
        status: 'CONFIRMED',
      },
      {
        id: 'RA-202608-011',
        amount: '19290.00',
        orderId: FULFILMENT_ORDER_ID,
        receiptId: 'RC-202608-011',
        status: 'CONFIRMED',
      },
    ],
    writeOffItems: [
      {
        id: 'WO-202608-1000-BAL',
        amount: '100.00',
        approvedAt: '2026-08-20',
        kind: 'CUSTOMER_BALANCE',
        orderId: FORMULA_ORDER_ID,
        remark: '使用客户历史预收余额',
        status: 'APPROVED',
      },
      {
        id: 'WO-202608-1000-WAV',
        amount: '20.00',
        approvedAt: '2026-08-20',
        kind: 'WAIVER',
        orderId: FORMULA_ORDER_ID,
        remark: '银行手续费差额与商务减免',
        status: 'APPROVED',
      },
    ],
    payments: [
      {
        id: 'PAY-202608-028-01',
        account: '招商银行基本户',
        allocations: [{ amount: '1704.00', purchaseOrderId: 'PO-202608-028' }],
        amount: '1704.00',
        currency: 'CNY',
        paidAt: '2026-08-22',
        status: 'CONFIRMED',
        supplierId: 'SUP-0028',
      },
    ],
    supplierInvoices: [
      {
        id: 'INV-202608-028-01',
        allocations: [{ amount: '2840.00', purchaseOrderId: 'PO-202608-028' }],
        amount: '2840.00',
        currency: 'CNY',
        invoiceNo: '33022608280001',
        issuedAt: '2026-08-25',
        status: 'PENDING_VERIFICATION',
        supplierId: 'SUP-0028',
      },
    ],
    orderExpenses: [
      {
        id: 'EXP-202608-011-01',
        amount: '6800.00',
        currency: 'CNY',
        expenseType: '订舱费',
        orderId: FULFILMENT_ORDER_ID,
        paymentMode: 'COMPANY_DIRECT',
        relatedId: 'SH-202608-011',
        relatedType: 'SHIPMENT',
        status: 'PENDING_APPROVAL',
      },
      {
        id: 'EXP-202608-011-02',
        amount: '520.00',
        currency: 'CNY',
        expenseType: '样品快递费',
        orderId: FULFILMENT_ORDER_ID,
        paymentMode: 'EMPLOYEE_REIMBURSEMENT',
        relatedId: FULFILMENT_ORDER_ID,
        relatedType: 'ORDER',
        status: 'APPROVED',
      },
    ],
    documentRelations: [
      {
        id: 'REL-ORDER-CUS-018',
        fromId: MAIN_ORDER_ID,
        fromType: 'ORDER',
        relationType: '交易客户',
        toId: 'CUS-1001',
        toType: 'CUSTOMER',
      },
      {
        id: 'REL-PR-ORDER-011',
        fromId: 'PR-202608-011',
        fromType: 'PURCHASE_REQUISITION',
        relationType: '来源订单',
        toId: FULFILMENT_ORDER_ID,
        toType: 'ORDER',
      },
      {
        id: 'REL-PO-PR-028',
        fromId: 'PO-202608-028',
        fromType: 'PURCHASE_ORDER',
        relationType: '来源采购申请',
        toId: 'PR-202608-011',
        toType: 'PURCHASE_REQUISITION',
      },
      {
        id: 'REL-SH-ORDER-011',
        fromId: 'SH-202608-011',
        fromType: 'SHIPMENT',
        relationType: '发货批次',
        toId: FULFILMENT_ORDER_ID,
        toType: 'ORDER',
      },
      {
        id: 'REL-RC-ORDER-1000',
        fromId: 'RC-202608-1000',
        fromType: 'RECEIPT',
        relationType: '回款分配',
        toId: FORMULA_ORDER_ID,
        toType: 'ORDER',
      },
      {
        id: 'REL-EXP-ORDER-011',
        fromId: 'EXP-202608-011-01',
        fromType: 'ORDER_EXPENSE',
        relationType: '订单费用',
        toId: FULFILMENT_ORDER_ID,
        toType: 'ORDER',
      },
    ],
    auditEvents: [
      {
        id: 'AUD-1001',
        action: `预读取 ${MAIN_ORDER_ID} 产品、库存与供应策略`,
        actor: 'AI 需求助手',
        createdAt: '2026-08-27T01:42:00.000Z',
        entityId: MAIN_ORDER_ID,
        entityType: 'ORDER',
        result: '仅准备建议，等待业务员点击运行分析',
        type: 'AI_SUGGESTION',
      },
      {
        id: 'AUD-1002',
        action: '同步 NOVA FITNESS GMBH 的 OKKI 基础资料',
        actor: '林晓月',
        createdAt: '2026-08-27T01:18:00.000Z',
        entityId: 'CUS-1001',
        entityType: 'CUSTOMER',
        result: '中台经营字段未被覆盖',
        type: 'HUMAN_CONFIRMATION',
      },
      {
        id: 'AUD-1003',
        action: '尝试直接修改包装箱库存数量',
        actor: 'AI 业务助手',
        createdAt: '2026-08-27T00:56:00.000Z',
        entityId: MAIN_ORDER_ID,
        entityType: 'ORDER',
        result: '已拒绝：库存只能通过正式库存单据改变',
        type: 'RULE_BLOCK',
      },
    ],
  };
}
